"""
    This .py can be edited with the
    handle_regex_based_on_input(self, url)
    function in ManualIdentifier
    (\d+)
    ([^/]+)
"""

"""
PROBLEMATIC OUTLETS: 
	coffeeordie.com		It does not have a distinctive URL pattern for profile pages...
"""

domain_url_regex = {
    'www.cityandstateny.com': r'https://www\.cityandstateny\.com/voices/([^/]+)/(\d+)/?$',
    'www.columbiamissourian.com': r'https://www\.columbiamissourian\.com/users/profile/([^/]+)/?$',
    'www.bizjournals.com': r'https://www\.bizjournals\.com/([^/]+)/bio/(\d+)/([^/]+)/?$',
    'www.ledger-enquirer.com': r'https://www\.ledger-enquirer\.com/profile/([^/]+)/?$',
    'www.commentary.org': r'https://www\.commentary\.org/author/([^/]+)/?$',
    'www.commondreams.org': r'https://www\.commondreams\.org/author/([^/]+)$',
    'rollcall.com': r'https://rollcall\.com/author/([^/]+)/$',
    'www.somerset-kentucky.com': r'https://www\.somerset-kentucky\.com/users/profile/([^/]+)/$',
    'www.cincinnati.com': r'https://www\.cincinnati\.com/staff/(\d+)/([^/]+)/$',
    'www.milwaukiereview.com': r'https://www\.milwaukiereview\.com/users/profile/([^/]+)/$',
    'cleantechnica.com': r'https://cleantechnica\.com/author/([^/]+)/$',
    'www.clevelandbanner.com': r'https://www\.clevelandbanner\.com/users/profile/([^/]+)$',
    'www.clevescene.com': r'https://www\.clevescene\.com/author/([^/]+)$',
	'www.chicagobusiness.com' : r'https://www\.chicagobusiness\.com/staff/([^/]+)/([^/]+)$',
	'www.crainsdetroit.com' : r'https://www\.crainsdetroit\.com/staff/([^/]+)$',
	'crooksandliars.com' : r'https://crooksandliars\.com/team/([^/]+)$',
	'cruiseradio.net' : r'https://cruiseradio\.net/author/([^/]+)/$',
	'www.cruisetradenews.com' : r'https://www\.cruisetradenews\.com/author/([^/]+)/$',
	'www.currentaffairs.org' : r'https://www\.currentaffairs\.org/author/([^/]+)$',
	'www.custercountychief.com' : r'https://www\.custercountychief\.com/users/profile/([^/]+)/$',
	'cyberscoop.com' : r'https://cyberscoop\.com/author/([^/]+)/$',
	'www.dailycamera.com' : r'https://www\.dailycamera\.com/author/([^/]+)/$',
	'www.houstonchronicle.com' : r'https://www\.houstonchronicle\.com/author/([^/]+)/$',
	'www.cincinnati.com' : r'https://www\.cincinnati\.com/staff/(\d+)/([^/]+)/$',
	'www.milwaukiereview.com' : r'https://www\.milwaukiereview\.com/users/profile/([^/]+)/$',
	'www.clintonherald.com' : r'https://www\.clintonherald\.com/users/profile/([^/]+)/$',
	'www.cnet.com' : r'https://www\.cnet\.com/profiles/([^/]+)/$',
	'www.cnn.com' : r'https://www\.cnn\.com/profiles/([^/]+)$',
	'www.coastalpoint.com' : r'https://www\.coastalpoint\.com/users/profile/([^/]+)/$',
	'coffeeordie.com' : r'https://coffeeordie\.com/([^/]+)$',
	'wkuherald.com' : r'https://wkuherald\.com/staff_name/([^/]+)/$',
	'www.columbiadailyherald.com' : r'https://www\.columbiadailyherald\.com/staff/(\d+)/([^/]+)/$',
	'www.columbiatribune.com' : r'https://www\.columbiatribune\.com/staff/(\d+)/([^/]+)/$',
	'www.somerset-kentucky.com' : r'https://www\.somerset-kentucky\.com/users/profile/([^/]+)/$',
	'www.concordmonitor.com' : r'https://www\.concordmonitor\.com/Byline?byline=([^/]+)$',
	'www.connectradio.fm' : r'https://www\.connectradio\.fm/author/([^/]+)$',
	'www.ctpost.com' : r'https://www\.ctpost\.com/author/([^/]+)/$',
	'consequence.net' : r'https://consequence\.net/author/([^/]+)/$',
	'www.conwaydailysun.com' : r'https://www\.conwaydailysun\.com/users/profile/([^/]+)/$',
	'www.americastestkitchen.com' : r'https://www\.americastestkitchen\.com/authors/([^/]+)$',
	'www.thetimestribune.com' : r'https://www\.thetimestribune\.com/users/profile/([^/]+)/$',
	'www.cosmopolitan.com' : r'https://www\.cosmopolitan\.com/author/(\d+)/([^/]+)/$',
	'www.mycentraljersey.com' : r'https://www\.mycentraljersey\.com/staff/(\d+)/([^/]+)/$',
	'www.thenewsstar.com' : r'https://www\.thenewsstar\.com/staff/(\d+)/([^/]+)/$',
	'www.dailyherald.com' : r'https://www\.dailyherald\.com/newsroom/([^/]+)/$',
	'www.yourvalley.net' : r'https://www\.yourvalley\.net/stories/([^/]+),(\d+)$',
	'dailyinterlake.com' : r'https://dailyinterlake\.com/staff/([^/]+)/$',
	'www.dailyitem.com' : r'https://www\.dailyitem\.com/users/profile/([^/]+)/$',
	'www.dailykos.com' : r'https://www\.dailykos\.com/users/([^/]+)$',
	'www.dailylobo.com' : r'https://www\.dailylobo\.com/staff/([^/]+)$',
	'www.dailylocal.com' : r'https://www\.dailylocal\.com/author/([^/]+)/$',
	'dailynorthwestern.com' : r'https://dailynorthwestern\.com/staff_name/([^/]+)/$',
	'www.dailypress.com' : r'https://www\.dailypress\.com/author/([^/]+)/$',
	'www.northjersey.com' : r'https://www\.northjersey\.com/staff/(\d+)/([^/]+)/$',
	'www.bizjournals.com' : r'https://www\.bizjournals\.com/dallas/bio/(\d+)/([^/]+)$',
	'www.newstimes.com' : r'https://www\.newstimes\.com/author/([^/]+)/$',
	'www.nytimes.com' : r'https://www\.nytimes\.com/by/([^/]+)$',
	'www.bloomberg.com' : r'https://www\.bloomberg\.com/authors/([^/]+)$',
	'www.reuters.com' : r'https://www\.reuters\.com/authors/([^/]+)/$',
	'www.forbes.com' : r'https://www\.forbes\.com/sites/([^/]+)/$',
	'www.washingtonpost.com' : r'https://www\.washingtonpost\.com/people/([^/]+)/$',
	'www.wsj.com' : r'https://www\.wsj\.com/news/author/([^/]+)$',
	'www.latimes.com' : r'https://www\.latimes\.com/people/([^/]+)$',
	'www.theguardian.com' : r'https://www\.theguardian\.com/profile/([^/]+)$',
	'www.nbcnews.com' : r'https://www\.nbcnews\.com/author/([^/]+)$',
	'www.usatoday.com' : r'https://www\.usatoday\.com/staff/(\d+)/([^/]+)/$',
	'www.foxnews.com' : r'https://www\.foxnews\.com/person/([^/]+)$',
	'www.npr.org' : r'https://www\.npr\.org/people/(\d+)/([^/]+)$',
	'abcnews.go.com' : r'https://abcnews\.go\.com/author/([^/]+)$',
	'www.dailymail.co.uk' : r'https://www\.dailymail\.co\.uk/profile-(\d+)/kelsi-karruli\.html$',
	'theathletic.com' : r'https://theathletic\.com/author/([^/]+)/$',
	'www.businessinsider.com' : r'https://www\.businessinsider\.com/author/([^/]+)$',
	'www.politico.com' : r'https://www\.politico\.com/staff/([^/]+)$',
	'www.bostonglobe.com' : r'https://www\.bostonglobe\.com/about/staff-list/staff/([^/]+)$',
	'nypost.com' : r'https://nypost\.com/author/([^/]+)/$',
	'www.newyorker.com' : r'https://www\.newyorker\.com/contributors/([^/]+)$',
	'www.si.com' : r'https://www\.si\.com/author/([^/]+)$',
	'www.inquirer.com' : r'https://www\.inquirer\.com/author/([^/]+)/$',
	'www.axios.com' : r'https://www\.axios\.com/authors/([^/]+)$',
	'www.startribune.com' : r'https://www\.startribune\.com/([^/]+)/(\d+)/$',
	'www.buzzfeed.com' : r'https://www\.buzzfeed\.com/([^/]+)$',
	'www.vice.com' : r'https://www\.vice\.com/en/contributor/([^/]+)$',
	'www.aljazeera.com' : r'https://www\.aljazeera\.com/author/([^/]+)$',
	'people.com' : r'https://people\.com/author/([^/]+)/$',
	'www.ajc.com' : r'https://www\.ajc\.com/staff/([^/]+)/$',
	'www.newsweek.com' : r'https://www\.newsweek\.com/authors/([^/]+)$',
	'www.sfchronicle.com' : r'https://www\.sfchronicle\.com/author/([^/]+)/$',
	'www.seattletimes.com' : r'https://www\.seattletimes\.com/author/([^/]+)/$',
	'www.huffpost.com' : r'https://www\.huffpost\.com/author/([^/]+)$',
	'www.dallasnews.com' : r'https://www\.dallasnews\.com/author/([^/]+)/$',
	'www.propublica.org' : r'https://www\.propublica\.org/people/([^/]+)$',
	'www.wnyc.org' : r'https://www\.wnyc\.org/people/([^/]+)/$',
	'time.com' : r'https://time\.com/author/([^/]+)/$',
	'nymag.com' : r'https://nymag\.com/author/([^/]+)/$',
	'www.vogue.com' : r'https://www\.vogue\.com/contributor/([^/]+)$',
	'variety.com' : r'https://variety\.com/author/([^/]+)/$',
	'seekingalpha.com' : r'https://seekingalpha\.com/author/([^/]+)$',
	'www.foxbusiness.com' : r'https://www\.foxbusiness\.com/person/([^/]+)$',
	'www.tampabay.com' : r'https://www\.tampabay\.com/author/([^/]+)/$',
	'fortune.com' : r'https://fortune\.com/author/([^/]+)/$',
	'www.rollingstone.com' : r'https://www\.rollingstone\.com/author/([^/]+)/$',
	'thehill.com' : r'https://thehill\.com/author/([^/]+)/$',
	'www.sbnation.com' : r'https://www\.sbnation\.com/authors/([^/]+)$',
	'www.usnews.com' : r'https://www\.usnews\.com/topics/author/([^/]+)$',
	'www.azcentral.com' : r'https://www\.azcentral\.com/staff/(\d+)/([^/]+)/$',
	'www.freep.com' : r'https://www\.freep\.com/staff/(\d+)/([^/]+)/$',
	'www.entrepreneur.com' : r'https://www\.entrepreneur\.com/author/([^/]+)$',
	'wgntv.com' : r'https://wgntv\.com/author/([^/]+)/$',
	'www.theadvocate.com' : r'https://www\.theadvocate\.com/users/profile/([^/]+)/$',
	'www.jsonline.com' : r'https://www\.jsonline\.com/staff/(\d+)/([^/]+)/$',
	'www.theepochtimes.com' : r'https://www\.theepochtimes\.com/author/([^/]+)$',
	'www.thedailybeast.com' : r'https://www\.thedailybeast\.com/author/([^/]+)$',
	'ktla.com' : r'https://ktla\.com/author/([^/]+)/$',
	'www.wbur.org' : r'https://www\.wbur\.org/inside/staff/([^/]+)$',
	'www.postandcourier.com' : r'https://www\.postandcourier\.com/users/profile/([^/]+)/$',
	'www.fool.com' : r'https://www\.fool\.com/author/([^/]+)/$',
	'www.vox.com' : r'https://www\.vox\.com/authors/([^/]+)$',
	'www.hollywoodreporter.com' : r'https://www\.hollywoodreporter\.com/author/([^/]+)/$',
	'www.kqed.org' : r'https://www\.kqed\.org/author/([^/]+)$',
	'www.marketwatch.com' : r'https://www\.marketwatch\.com/author/([^/]+)$',
	'www.reviewjournal.com' : r'https://www\.reviewjournal\.com/staff/([^/]+)/$',
	'www.ksat.com' : r'https://www\.ksat\.com/team/([^/]+)/$',
	'www.science.org' : r'https://www\.science\.org/content/author/([^/]+)$',
}